# Generated by Django 6.0.2 on 2026-02-18 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_out', models.DateField()),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('rental_fee', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='customers.customer')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='movies.movie')),
            ],
        ),
    ]
